package core

import (
	"context"
	"encoding/json"
	"os/exec"
	"reflect"
	"strings"
	"testing"
)

func reviewFixture(t *testing.T) string {
	t.Helper()
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("Git unavailable")
	}
	root := t.TempDir()
	testGit(t, root, "init")
	put(t, root, "go.mod", "module example.test/review\n\ngo 1.27.1\n")
	put(t, root, "main.go", "package main\nfunc main(){ Before() }\nfunc Before(){}\n")
	put(t, root, "main_test.go", "package main\nimport \"testing\"\nfunc TestMain(t *testing.T){ Before() }\n")
	testGit(t, root, "add", ".")
	testGit(t, root, "commit", "-m", "Base fixture")
	return root
}
func TestReviewLocalChangesAndStableOrder(t *testing.T) {
	root := reviewFixture(t)
	put(t, root, "main.go", "package main\nfunc main(){ After() }\nfunc After(){}\n")
	put(t, root, "new.go", "package main\nfunc Added(){}\n")
	put(t, root, ".gitignore", "private.go\n")
	put(t, root, "private.go", "package main\nfunc Secret(){}\n")
	idx, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	repo := NewRepository(idx)
	before := testGit(t, root, "status", "--porcelain=v1")
	review, err := repo.Review(context.Background(), "HEAD")
	if err != nil {
		t.Fatal(err)
	}
	if review.Files != 2 {
		t.Fatalf("files: %d", review.Files)
	}
	assertReviewChanges(t, review)
	again, err := repo.Review(context.Background(), "HEAD")
	if err != nil {
		t.Fatal(err)
	}
	a, _ := json.Marshal(review)
	b, _ := json.Marshal(again)
	if !reflect.DeepEqual(a, b) {
		t.Fatal("nondeterministic review")
	}
	if after := testGit(t, root, "status", "--porcelain=v1"); before != after {
		t.Fatal("review modified Git state")
	}
}
func assertReviewChanges(t *testing.T, review ChangeReview) {
	t.Helper()
	statuses := map[string]string{}
	for _, change := range review.Changes {
		statuses[change.Node.Name] = change.Status
		if strings.Contains(change.Node.Path, "private") {
			t.Fatal("private source included")
		}
	}
	if statuses["func Before"] != "removed" || statuses["func After"] != "added" || statuses["func main"] != "modified" || statuses["func Added"] != "added" {
		t.Fatalf("changes: %v", statuses)
	}
	for _, change := range review.Changes {
		if change.Node.Name == "func main" && (len(change.RelationshipsAdded) == 0 || len(change.RelationshipsRemoved) == 0) {
			t.Fatal("missing relationship delta")
		}
	}
}

func TestReviewGeneratedContextAndSubdirectory(t *testing.T) {
	root := reviewFixture(t)
	put(t, root, "sub/generated.go", "// Code generated by fixture. DO NOT EDIT.\npackage sub\nfunc Work(){}\n")
	put(t, root, "sub/part.go", "package sub\nvar Count=1\nfunc Stable(){}\n")
	testGit(t, root, "add", ".")
	testGit(t, root, "commit", "-m", "Subdirectory")
	put(t, root, "sub/generated.go", "// Code generated by fixture. DO NOT EDIT.\npackage sub\nfunc Work(){ println(2) }\n")
	put(t, root, "sub/part.go", "package sub\nvar Count=2\nfunc Stable(){}\n")
	idx, err := Scan(root + "/sub")
	if err != nil {
		t.Fatal(err)
	}
	review, err := NewRepository(idx).Review(context.Background(), "HEAD")
	if err != nil {
		t.Fatal(err)
	}
	if review.Files != 2 || review.GeneratedFiles != 1 || len(review.Changes) != 1 || review.Changes[0].Status != "file context changed" {
		t.Fatalf("review %#v", review)
	}
}
func TestReviewRejectsMissingBaseAndStaleSource(t *testing.T) {
	root := reviewFixture(t)
	idx, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	repo := NewRepository(idx)
	for _, base := range []string{"--help", "does-not-exist", "HEAD\n"} {
		if _, err := repo.Review(context.Background(), base); err == nil {
			t.Fatalf("accepted %q", base)
		}
	}
	put(t, root, "main.go", "package main\nfunc Changed(){}\n")
	if _, err := repo.Review(context.Background(), "HEAD"); err == nil {
		t.Fatal("stale comparison allowed")
	}
}

func TestReviewPreservesRelatedTestsAndModuleIdentity(t *testing.T) {
	root := reviewFixture(t)
	put(t, root, "main.go", "package main\nfunc main(){ Before() }\nfunc Before(){println(1)}\n")
	idx, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	review, err := NewRepository(idx).Review(context.Background(), "HEAD")
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, change := range review.Changes {
		if change.Node.Name == "func Before" {
			for _, next := range change.Related {
				if next.Relationship == "tested-by" {
					found = true
				}
			}
		}
	}
	if !found {
		t.Fatal("related test missing")
	}
	put(t, root, "go.mod", "module changed.test/review\n")
	if err := idx.CheckPolicy(); err == nil {
		t.Fatal("module identity changes must invalidate the snapshot")
	}
}
